package main

import (
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	"log"
	"uji/database"
	userhandler "uji/users/delivery/http"
	userrepository "uji/users/repository/postgre"
	userusecase "uji/users/usecase"
)

// @title MyGram
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /users

func main() {
	db, err := database.InitDatabase()
	if err != nil {
		log.Fatal(err)
	}

	posgreDB, err := db.DB()
	err = posgreDB.Ping()
	if err != nil {
		log.Fatal(err)
	}

	defer func() {
		err := posgreDB.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()

	e := echo.New()
	e.Use(middleware.Recover())

	// Serve Swagger documentation
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	userRepo := userrepository.NewUserRepsitory(db)
	userUseCase := userusecase.NewUserUseCase(userRepo)
	userhandler.NewUserHandler(e, userUseCase, db)

	e.Start(":8000")

}
